replicaCount: 1

webapp:
  name: gaiafuture
  group: gaiafuture
  path: /
  tls:
    fqdn: gaiafuture.k8s.ucar.edu
    secretName: incommon-cert-gaiafuture
  container: 
    image: hmchilders/paneltestbed1:latest
    port: 5003
    memory: 1G
    cpu: 2